CREATE TABLE "GCG_4586_Router"(
 "ID" IDENTITY DEFAULT '0',
 "Screen" CHAR(50) NOT NULL ,
 "Router" CHAR(20) NOT NULL ,
 "Router_Seq" CHAR(6) NOT NULL ,
 "Customer" CHAR(50),
 "MLCat" CHAR(50),
 "Part_Desc" CHAR(50),
 "CustomerPartNum" CHAR(50),
 "Product_line" CHAR(50),
 "Code" CHAR(50),
 "Wall" CHAR(50),
 "AWG" CHAR(50),
 "H_Length" CHAR(50),
 "DataReqFinal" BIT DEFAULT '0' NOT NULL ,
 "FinalInspce" BIT DEFAULT '0' NOT NULL ,
 "Engineer" CHAR(50),
 "QA" CHAR(50),
 "EngDate" DATE DEFAULT '1900-01-01' NOT NULL ,
 "QADate" DATE DEFAULT '1900-01-01' NOT NULL ,
 "Header_Notes" LONGVARCHAR,
 "LHR_NO" CHAR(50),
 "Procedure_No" CHAR(50),
 "Form_No" CHAR(50),
 "DataReqInProc" BIT DEFAULT '0' NOT NULL ,
 "Assy_Inst" LONGVARCHAR,
 "Inspection_Inst" LONGVARCHAR,
 "Pull" CHAR(50),
 "Flush" CHAR(50),
 "Dry" CHAR(50),
 "Pulling_Inst" LONGVARCHAR,
 "Flushing_Inst" LONGVARCHAR,
 "Baking_Inst" LONGVARCHAR,
 "Task_Type" CHAR(50),
 "QA_Inst" LONGVARCHAR,
 "Rein_type" CHAR(50),
 "Carrier_Pattern" CHAR(50),
 "Braid_Size" CHAR(50),
 "Braid_Matl" CHAR(50),
 "PPI" CHAR(50),
 "WPI" CHAR(50),
 "Transition" BIT DEFAULT '0' NOT NULL ,
 "Var_Dist" CHAR(50),
 "Tran_Dist" CHAR(50),
 "Axial" CHAR(50),
 "Axial_NO" CHAR(50),
 "Axial_Size" CHAR(50),
 "Axial_Matl" CHAR(50),
 "Axial_Post" CHAR(50),
 "Rein_Notes" CHAR(50),
 "Top_Type" CHAR(50),
 "Top_Color" CHAR(50),
 "Top_ID_Min" CHAR(50),
 "Top_ID_Max" CHAR(50),
 "Top_ID_Nom" CHAR(50),
 "Top_ID_Tol" CHAR(50),
 "Top_OD_Min" CHAR(50),
 "Top_OD_Max" CHAR(50),
 "Top_OD_Nom" CHAR(50),
 "Top_OD_Tol" CHAR(50),
 "Top_Wall_Min" CHAR(50),
 "Top_Wall_Max" CHAR(50),
 "Top_Wall_Nom" CHAR(50),
 "Top_Wall_Tot" CHAR(50),
 "Top_OD_Min_API" BIT DEFAULT '0' NOT NULL ,
 "Top_OD_Max_API" BIT DEFAULT '0' NOT NULL ,
 "Top_OD_Nom_API" BIT DEFAULT '0' NOT NULL ,
 "Top_OD_Tot_API" BIT DEFAULT '0' NOT NULL ,
 "Top_Wall_Min_API" BIT DEFAULT '0' NOT NULL ,
 "Top_Wall_Max_API" BIT DEFAULT '0' NOT NULL ,
 "Top_Wall_Nom_API" BIT DEFAULT '0' NOT NULL ,
 "Top_Wall_Tot_API" BIT DEFAULT '0' NOT NULL ,
 "Top_Notes" LONGVARCHAR,
 "Trim_Type" CHAR(50),
 "Trim_At" CHAR(50),
 "Trim_Len_Min" CHAR(50),
 "Trim_Len_Max" CHAR(50),
 "Trim_Len_Nom" CHAR(50),
 "Trim_Tol" CHAR(50),
 "Trim_Notes" LONGVARCHAR NOT NULL ,
 UNIQUE ("ID"));
